export const ACTION_TYPES = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
  
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",

  SET_CURRENT_USER: "SET_CURRENT_USER",

  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",

  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",

  SHOW_MORE_PRODUCTS: "SHOW_MORE_PRODUCTS",

  SORT_PRODUCTS: "SORT_PRODUCTS",
}